# EDS 217 Day 3 (Friday) Notes
## 2023-09-08



## Session 2-2: Structured Data in Python

- like spreadsheets
- rows, columns


### Dictionaries


key: value
You can create a dictionary using the `{}`, providing both a `key` and a `value`, which are separated by a `:`.

In [ ]:
environmental_disciplines = {
    'ecology':'The relationships between organisms and their environments.',
    'hydrology':'The properties, distribution & effects of water on the surface, subsurface, & atmosphere.',
    'geology':'The origin, history, and structure of the earth.',
    'meteorology':'The phenomena of the atmosphere, especially weather and weather conditions.'
    }

In [ ]:
# accessing elements

environmental_disciplines['ecology']

you will get a NameError if you try:

environmental_disciplines[ecology]

because the variable ecology has not been defined

In [ ]:
# dictionaries are mutable

environmental_disciplines['geomorphology'] = 'The evolution and configuration of landforms'

In [ ]:
environmental_disciplines['geomorphology']

- can only look up values by keys, not position

In [ ]:
# values in the dictionary are not indexed -- can't call with [0] or [n]

environmental_disciplines[0]


if we define a variable with the same keyword as the key, we can use that to access the value stored in that key

In [ ]:
this_discipline = 'ecology'

print(environmental_disciplines[this_discipline])

if you spell the key incorrectly or use a key that doesn't exist, you will get a KeyError

A NameError indicates that you're doing the wrong thing to access a variable (kind of like syntax but not?)

In [ ]:
environmental_disciplines['biogeochemistry'] = 'the chemical, physical, geological, and biological processes and reactions that govern the composition of the natural environment.'
print(environmental_disciplines['biogeochemistry'])

#### built-in `key()` and `values()` functions in dictionaries

In [ ]:
definitions = environmental_disciplines.values()
print(definitions)


. notation

In [ ]:
environmental_disciplines.keys()

these functions return a dict_keys and dict_values objects respectively. These objects contain a list of keys or values. you can force the result of these functions into a list by wrapping either one in a list() command

In [ ]:
environmental_disciplines.values()

In [ ]:
key_list = list(environmental_disciplines.keys())
print(key_list)

values_list = list(environmental_disciplines.values())

.items() is a property of any dictionary

In [ ]:
for key, value in environmental_disciplines.items():
    print(key, value)
   # environmental_disciplines[key] = value.capitalize()

In [ ]:
my_dict = {'name': 'Homer Simpson',
           'occupation': 'Nuclear Engineer',
           'address': '742 Evergreen Terrace',
           'city': 'Springfield',
           'state': ' ? '
          }

for key, value in my_dict.items():
    print(f"{key.capitalize()}: {value}.")

In [ ]:
for key, value in environmental_disciplines.items():
    print(f"{key.title()} is the study of {value.lower()}")

`len()` used for list indices 

`get()` function used to avoid errors when requesting an element from a **dict** -- `get()` returns `None` if the element doesn't exist (default)

you can specify a "default" value which will be returned for any undefined elements

In [ ]:
environmental_disciplines.get('xenohydrology', 'Discipline not defined.')

xenohydrology_definition = environmental_disciplines.get('xenohydrology', 'Discipline not defined.')

print(xenohydrology_definition)

In [ ]:
list_of_disciplines = ['climatology', 'ecology', 'meteorology', 'geology', 'biogeochemistry']

In [ ]:
for discipline in list_of_disciplines:
    definition = environmental_disciplines.get(discipline, '[not defined]')
    #print(f"The ")
    print(f"{discipline} is the study of {definition}")

In [ ]:
my_list = list([2, 3, 4, 6, 1])

min(my_list)
# .append is one of many *methods* that any list can have
my_list.append(12)
print(my_list)


import numpy as np


In [ ]:
np.append(my_list, 13)

*don't* do:

from numpy import * 

what can we get away with in terms of key assignments in dictionaries

In [ ]:
test_dict = dict({
    3: 'the number three',
    len: 'the function len'
})

print(test_dict)

In [ ]:
dict_2 = dict({
    'a': 3,
    'b': len,
    'c': dict({'a': 5}),
    'a': 4 # this overrides the earlier a:3
})

print(dict_2)

## Interactive session 3-1: NumPy

### NumPy Arrays


- partly built on C, important because it allows it to scale ??

In [1]:
import os
import math
import random
import datetime as dt
import numpy as np

In [2]:
# os. # lots of options :) 
# all of these imports are modules

# usually in the syntax: import [module] as [name]
type(math)

module

n-dimensional array object in NumPy = `ndarray`
- all values in the array are the same type and size
- can be 1D - (one row or column vector)
- can be 2D - (*m* rows x *n* columns)
can be 3D - (arrays within arrays)

#### Constructing arrays from lists

In [3]:
np.array([8, 0, 9, 1, 4])

array([8, 0, 9, 1, 4])

In [4]:
my_list = list([4, 5, 6, 7, 8])
my_array = np.array([4, 5, 6, 7, 8])

my_list == my_array # returns array of true or false for each value pair
# my_list2 = list([4, 5, 6, 8, 9])
# my_list == my_list2 # returns False

array([ True,  True,  True,  True,  True])

In [7]:
np.array([[8,0,9,1,4]]) # row vector with 5 columns

array([[8, 0, 9, 1, 4]])

In [8]:
a = np.array([[3,2,0,1],[9,1,8,7],[4,0,1,6]]) # array with 3 rows x 4 columns
print(a)

[[3 2 0 1]
 [9 1 8 7]
 [4 0 1 6]]


## 📚  **Practice 1.**  
Create the following arrays and assign the corresponding variable names:

1. `a`  
    $$
    \begin{bmatrix}
        4 & 5 & 0 & 12 & -1 \\
        8 & -21 & -4 & 6 & 3 \\
        17 & 1 & -13 & 7 & 0
    \end{bmatrix}
    $$


In [ ]:
a = np.array([[4, 5, 0, 12, -1], [8, -21, -4, 6, 3], [17, 1, -13, 7, 0]])
print(a)

[[  4   5   0  12  -1]
 [  8 -21  -4   6   3]
 [ 17   1 -13   7   0]]



2. `b`  
    $$
    \begin{bmatrix}
        1.0 & 2.7 & 0 & 0.188 & 4.07 & 0.24
    \end{bmatrix}
    $$


In [ ]:
b = np.array([[1.0, 2.7, 0, 0.188, 4.07, 0.24]])
print(b)

[[1.    2.7   0.    0.188 4.07  0.24 ]]


3. `c`  
    $$
    \begin{bmatrix}
        0.4 \\
        0.8 \\
        1.2 \\
        1.6 \\
        2.0 \\
        2.4
    \end{bmatrix}
    $$

In [ ]:
c = np.array([[0.4], [0.8], [1.2], [1.6], [2.0], [2.4]])
print(c)

[[0.4]
 [0.8]
 [1.2]
 [1.6]
 [2. ]
 [2.4]]


#### constructing arrays using functions

using `np.arange()` to generate an array with evenly spaced values within a given interval -- 3 parameters: start, stop, step (like `seq()` in R)

In [9]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
np.arange(1., 13.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [11]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

`np.linspace()`  (linear space)
- instead of *step* parameter, takes *num* parameter to specify the number of samples within the given interval
- includes the *stop* value by default
- recommended to use linspace when a non-integer step (like 0.25) is desired

In [16]:
np.linspace(0, 1, 5) # starting from 0, to (inclusive) 1, 5 evenly spaced numbers

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
d = np.arange(0, 100, 3)
print(d)

f = np.linspace(0, 2, 10)
print(f)

g = np.linspace(0.4, 2.4, 6)
f = g.reshape(-1, 1) # you can also write (6, 1) or (len(g),1)
f

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


array([[0.4],
       [0.8],
       [1.2],
       [1.6],
       [2. ],
       [2.4]])

`np.zeros(4)` creates a 1D array of zeros of length 4

`np.zeros(rows, columns)`

`np.ones(rows, columns)`

In [22]:
np.zeros(4)

array([0., 0., 0., 0.])

In [25]:
np.ones((4, 3)) # default is float, can specify , int 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.full((4,3),9.87)

array([[9.87, 9.87, 9.87],
       [9.87, 9.87, 9.87],
       [9.87, 9.87, 9.87],
       [9.87, 9.87, 9.87]])

In [19]:
np.random.rand(4, 3)

array([[0.65899006, 0.88020194, 0.179569  ],
       [0.68970373, 0.02146483, 0.90768381],
       [0.20480017, 0.05263119, 0.34935522],
       [0.5964428 , 0.01072708, 0.13795201]])

In [21]:
np.eye(4) # creates 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

| Method | Description |
| :----- | :---------- |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> ndarray.ndim </span> | Number of array dimensions |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> ndarray.shape </span> | Tuple of array dimensions (*rows*, *columns*) |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> ndarray.size </span> | Total number of elements in the array |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> ndarray.dtype </span> | Data-type of array elements |

In [30]:
# Initialize array
a = np.random.rand(4,7)

# Determine array dimensions
a.ndim
# >>> 2


2

In [33]:

# Determine array shape
a.shape
# >>> (4, 7)


(4, 7)

In [32]:

# Determine array size
a.size
# >>> 28


28

In [ ]:

# Determine data-type
a.dtype
# >>> dtype('float64')

In [36]:
d.size

34

### Indexing and Slicing

In [38]:
x1 = np.array([8, 0, 9, 1, 4])

x1[1]

0

`ndarray[row,column]` -- if single index is passed, corresponding row element is returned

In [39]:
x2 = np.array([[3,2,0,1],
               [9,1,8,7],
               [4,0,1,6]])

In [46]:
x2[0][0]

3

In [40]:
x2[1,2]

8

In [47]:
x2[1][2]

8

In [42]:
x2[1]

array([9, 1, 8, 7])

In [41]:
x2[1:]

array([[9, 1, 8, 7],
       [4, 0, 1, 6]])

For multidimensional arrays, a tuple of slices is used: `ndarray[row_start:row_end:row_step, col_start:col_end:col_step]`.

In [44]:
x2[:,2] # returns the entire third column

array([0, 8, 1])

In [45]:
# returns the first two rows and two columns

x2[:2, :2]

array([[3, 2],
       [9, 1]])

In [48]:
# Return all rows and every other column
x2[:,::2]

array([[3, 0],
       [9, 8],
       [4, 1]])

x2.mean(axis=1) # mean of each row, calculated across columns

x2.max(axis=0) # max value of each column (calculated across rows)

In [52]:
x2
x2.mean(axis=1) == np.mean(x2, axis=1)

array([ True,  True,  True])

In [53]:
print(x2)

[[3 2 0 1]
 [9 1 8 7]
 [4 0 1 6]]


In [55]:
print(x2.reshape(4,3))

[[3 2 0]
 [1 9 1]
 [8 7 4]
 [0 1 6]]


In [59]:
m = np.arange(1.0, 17.0)
print(m)
n = m.reshape(4,4)
print(n)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


- needs to preserve the size
- `.reshape()` creates a **view** of the original array, rather than a **copy**
- anything you do to the defined reshape will also impact the thing you reshaped

- resizing can add or delete rows and/or columns
- make a copy of the original array 

In [63]:
y = np.array([[1,2,3], [4,5,6]])
poppy = y.copy()
print(y)
poppy.resize(2,2)
poppy

preppy = y.copy()
preppy.resize(6,6)
preppy

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3, 4, 5, 6],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

- `ndarray.transpose()` = `ndarray.T` transposes the array, switching rows and columns

- `np.flip()` flips the array -- reverse order of all the individual elements
- `np.flipud()` flips array up/down in reverse order of the rows
- `np.fliplr()` flips the array left/right (reverse the order of columns)
- in all of the flip functions, axis=0 and axis=1  impact what the array is flipped over (0=row axis, 1=column axis)

In [65]:
x2

array([[3, 2, 0, 1],
       [9, 1, 8, 7],
       [4, 0, 1, 6]])

In [66]:
x2.T

array([[3, 9, 4],
       [2, 1, 0],
       [0, 8, 1],
       [1, 7, 6]])

In [67]:
np.flip(x2)

array([[6, 1, 0, 4],
       [7, 8, 1, 9],
       [1, 0, 2, 3]])

In [68]:
np.flipud(x2)

array([[4, 0, 1, 6],
       [9, 1, 8, 7],
       [3, 2, 0, 1]])

In [69]:
np.fliplr(x2)

array([[1, 0, 2, 3],
       [7, 8, 1, 9],
       [6, 1, 0, 4]])