| [⬅️ Previous Session](practice_2-2_structured_data.ipynb) | [🏠 Course Home](../index.ipynb) | [➡️ Next Session](practice_4-1_pandas.ipynb) |

# Practice 3-1: Introduction to NumPy


<div class="run">
    ▶️ <b> Run the cell below. </b>
</div>


In [2]:
# Imports
import numpy as np


## 📚  **Practice 1.**  
Create the following arrays and assign the corresponding variable names:

1. `a`  
    $$
    \begin{bmatrix}
        4 & 5 & 0 & 12 & -1 \\
        8 & -21 & -4 & 6 & 3 \\
        17 & 1 & -13 & 7 & 0
    \end{bmatrix}
    $$

2. `b`  
    $$
    \begin{bmatrix}
        1.0 & 2.7 & 0 & 0.188 & 4.07 & 0.24
    \end{bmatrix}
    $$

3. `c`  
    $$
    \begin{bmatrix}
        0.4 \\
        0.8 \\
        1.2 \\
        1.6 \\
        2.0 \\
        2.4
    \end{bmatrix}
    $$


In [5]:
a = np.array([[4, 5, 0, 12, -1], [8, -21, -4, 6, 3], [17, 1, -13, 7, 0]])
print(a)

b = np.array([[1.0, 2.7, 0, 0.188, 4.07, 0.24]])
print(b)

c = np.array([[0.4], [0.8], [1.2], [1.6], [2.0], [2.4]])
print(c)

[[  4   5   0  12  -1]
 [  8 -21  -4   6   3]
 [ 17   1 -13   7   0]]
[[1.    2.7   0.    0.188 4.07  0.24 ]]
[[0.4]
 [0.8]
 [1.2]
 [1.6]
 [2. ]
 [2.4]]


## 📚  <b> Practice 2. </b> 
<ol class="alpha">
<li> Create a new array <code>d</code> of integers the multiples of 3 between 0 and 100.</li>
<li> Create an array <code>f</code> 10 evenly spaced elements between 0 and 2.</li> 
<li> Re-create array <code>c</code> from Practice 1c using a function. Assign this to variable name <code>g</code>. </li>
</ol>    

In [3]:
d = np.arange(0, 100, 3)
print(d)

f = np.linspace(0, 2, 10)
print(f)

g = np.linspace(0.4, 2.4, 6)
f = g.reshape(-1, 1)
f

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


array([[0.4],
       [0.8],
       [1.2],
       [1.6],
       [2. ],
       [2.4]])

## 📚  <b> Practice 3. </b> Assign the following to variables:
<ol class="alpha">
    <li> A 5x3 array of ones. </li>
    <li> A one-dimensional array of 6 zeros. </li> 
    <li> A 7x7 identity array. </li>
    <li> A random 10x10 array. </li>
</ol>

In [6]:
big_ones = np.ones((5, 3))
big_ones

six_o = np.zeros(6)
six_o

sev = np.eye(7)
sev

ten_r = np.random.rand(10, 10)
ten_r

array([[0.53643308, 0.26299143, 0.58222826, 0.46282818, 0.40225151,
        0.52414325, 0.68088233, 0.85951816, 0.3038113 , 0.49095346],
       [0.70255323, 0.23173392, 0.64543985, 0.21988705, 0.43984042,
        0.3150801 , 0.35208903, 0.31419483, 0.13803026, 0.2093145 ],
       [0.72562962, 0.95221793, 0.94575114, 0.89435156, 0.38417358,
        0.68257077, 0.79794989, 0.26058069, 0.4956617 , 0.43364106],
       [0.90238468, 0.9459533 , 0.8274205 , 0.23862764, 0.12218913,
        0.80737113, 0.23696453, 0.96308737, 0.74465084, 0.50499848],
       [0.77505461, 0.28909793, 0.79172185, 0.68417296, 0.20286906,
        0.18861216, 0.21718496, 0.63224423, 0.13105543, 0.24668595],
       [0.12212002, 0.77047246, 0.07543254, 0.21437494, 0.34058746,
        0.91023707, 0.4816695 , 0.22166802, 0.41269367, 0.35683735],
       [0.88101652, 0.09704907, 0.79821147, 0.99295162, 0.36292538,
        0.01306863, 0.41645526, 0.63073669, 0.73215422, 0.02376269],
       [0.51530662, 0.59689787, 0.4873560

## 📚  <b> Practice 4. </b> 
Use array methods and the array you created in Practice 2a (<code>d</code>) to count the number of multiples of 3 between 0 and 100.


In [7]:
d.size

34


## 📚  <b> Practice 5. </b> Using the array you created in Practice 3d,
<ol class="alpha">
    <li> Print all the elements in column 4. </li>
    <li> Print all the elements in row 7. </li>
    <li> Extract the 4x4 subarray at the center of the array and assign it as a new variable. </li>
    <li> Print the last two values in column 10. </li>
</ol>

In [20]:
ten_r = np.random.rand(10, 10)
print(ten_r)


[[0.72726993 0.23493041 0.7505338  0.05608077 0.15986862 0.43206356
  0.00168279 0.05421937 0.30967571 0.62946039]
 [0.1281782  0.98286262 0.88644267 0.70594149 0.31522481 0.67680671
  0.09026066 0.44243719 0.25671182 0.30445976]
 [0.65622088 0.93492952 0.09863138 0.47734696 0.08613358 0.14403585
  0.35633711 0.66861906 0.62019191 0.01795272]
 [0.21721413 0.69436251 0.22196616 0.16577091 0.43070568 0.11846508
  0.20208677 0.6725347  0.93734201 0.04964409]
 [0.52201231 0.62685388 0.85406144 0.00968274 0.6809229  0.87024639
  0.1190617  0.73904607 0.95421228 0.04304389]
 [0.75631601 0.74256608 0.42079757 0.64105693 0.35277868 0.93956318
  0.34597832 0.94959508 0.80513795 0.93777319]
 [0.11180499 0.2268258  0.29412135 0.11712849 0.49104647 0.60933743
  0.45752946 0.20461969 0.85582277 0.23141571]
 [0.1832486  0.18925908 0.00288771 0.12938239 0.5496794  0.01243169
  0.8600632  0.18371879 0.29742723 0.84363395]
 [0.68368598 0.13837721 0.27630038 0.61190256 0.97461498 0.49675507
  0.22780471

In [24]:
# Print all the elements in column 4.
print(ten_r[:,3])

[0.05608077 0.70594149 0.47734696 0.16577091 0.00968274 0.64105693
 0.11712849 0.12938239 0.61190256 0.42983782]


In [27]:
# Print all the elements in row 7. 
print(ten_r[6])
# or
print(ten_r[6,:])

[0.11180499 0.2268258  0.29412135 0.11712849 0.49104647 0.60933743
 0.45752946 0.20461969 0.85582277 0.23141571]
[0.11180499 0.2268258  0.29412135 0.11712849 0.49104647 0.60933743
 0.45752946 0.20461969 0.85582277 0.23141571]


In [30]:
# Extract the 4x4 subarray at the center of the array 
# and assign it as a new variable.

mid = (ten_r[3:7, :])

mid.shape

(4, 10)

In [31]:
center = ten_r[3:7, 3:7]
center.shape

(4, 4)

In [35]:
# Print the last two values in column 10.

# return the values from the rows from index 8 onwards (row 9 and 10)
# in column 10 (index 9)
ten_r[8:,9]

array([0.00811164, 0.05793224])

## 📚  <b> Practice 6. </b> 
Create a blank 8x8 matrix and fill it with a checkerboard pattern of 0s and 1s using indexing.


In [36]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [44]:
x = np.zeros((8, 8))
x
x[1::2, ::2] = 1
x
x[::2, 1::2] = 1
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [57]:
galaxy_checkers = np.indices((8,8)).sum(axis=0) # % 2
galaxy_checkers

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 4,  5,  6,  7,  8,  9, 10, 11],
       [ 5,  6,  7,  8,  9, 10, 11, 12],
       [ 6,  7,  8,  9, 10, 11, 12, 13],
       [ 7,  8,  9, 10, 11, 12, 13, 14]])

## 📚  <b> Practice 7. </b>
<ol class="alpha">
    <li> Create a 3x3 matrix with values ranging from 0 to 8. </li>
    <li> Reverse the order of elements in your random 10x10 array from 3d. </li>
</ol>

In [59]:
values = np.arange(0, 9)
shaped = values.reshape(3,3)
# tbt[:,:] = np.arange(0,9)
shaped

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
np.flip(ten_r)

array([[0.05793224, 0.01627967, 0.24816409, 0.04265795, 0.47950288,
        0.95677958, 0.42983782, 0.00489646, 0.62876556, 0.80652632],
       [0.00811164, 0.08106206, 0.56690391, 0.22780471, 0.49675507,
        0.97461498, 0.61190256, 0.27630038, 0.13837721, 0.68368598],
       [0.84363395, 0.29742723, 0.18371879, 0.8600632 , 0.01243169,
        0.5496794 , 0.12938239, 0.00288771, 0.18925908, 0.1832486 ],
       [0.23141571, 0.85582277, 0.20461969, 0.45752946, 0.60933743,
        0.49104647, 0.11712849, 0.29412135, 0.2268258 , 0.11180499],
       [0.93777319, 0.80513795, 0.94959508, 0.34597832, 0.93956318,
        0.35277868, 0.64105693, 0.42079757, 0.74256608, 0.75631601],
       [0.04304389, 0.95421228, 0.73904607, 0.1190617 , 0.87024639,
        0.6809229 , 0.00968274, 0.85406144, 0.62685388, 0.52201231],
       [0.04964409, 0.93734201, 0.6725347 , 0.20208677, 0.11846508,
        0.43070568, 0.16577091, 0.22196616, 0.69436251, 0.21721413],
       [0.01795272, 0.62019191, 0.6686190


## 📚  <b> Practice 8. </b> 
Create two random 1-D arrays of length 10. Merge them into a 2x10 array and then a 10x2 array.


In [1]:
import numpy as np

In [4]:
xa = np.array([[4, 2, 0, 1, 5],
              [9, 4, 1, 3, 0],
              [6, 0, 8, 5, 9],
              [7, 3, 2, 7, 4]])

xb = np.array([[4,2,0],
              [9,4,1],
              [6,0,8]])

ya = np.array([[2,8,6]])

In [6]:
np.concatenate((xb, ya))

array([[4, 2, 0],
       [9, 4, 1],
       [6, 0, 8],
       [2, 8, 6]])


## 📚  <b> Practice 9. </b>
<ol class="alpha">
    <li> Split your random 10x10 array from 3d into two 10x5 arrays. </li>
    <li> Combine the first 10x5 array from (a), the 10x2 array from 8b, and the other 10x5 array from (a). In other words, recombine the 10x10 array from 3d with two new columns in index positions 5 and 6. Your final array should have 10 rows and 12 columns. Verify this by printing the shape of the resulting array. </li>
</ol>



## 📚  <b> Practice 10. </b>
<ol class="alpha">
    <li> Raise array <code>b</code> to the power of array <code>c</code>. </li>
    <li> Create a new 5x10 array of random values. Subtract the mean of each row from every value. </li>
</ol>


<hr style="border-top: 1px solid gray; margin-top: 24px; margin-bottom: 1px"></hr>